---
fixtures:
  repositories:
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      tag: 3.1.0
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      tag: 4.13.1
  symlinks:
    iptables: "#{source_dir}"
